import { createHash, randomUUID } from 'node:crypto';
import { promises as fs } from 'node:fs';
import { dirname } from 'node:path';
import { z } from 'zod';
import { ClipboardStorage } from './clipboard-storage';
import {
  DEFAULT_CLIPBOARD_PREFERENCES,
  type ClipboardClip,
  type ClipboardPreferences,
} from '../shared/clipboard';

export const MAX_IMAGE_BYTES = 32 * 1024 * 1024;
// Images are stored as base64. Apply the image limit to PNG bytes, not its encoded string.
export const MAX_CLIP_BYTES = Math.ceil(MAX_IMAGE_BYTES / 3) * 4;
export const MAX_HISTORY_BYTES = 128 * 1024 * 1024;
export const MAX_HISTORY_ITEMS = 200;
const preferencesSchema = z.object({
  paused: z.boolean(),
  pauseUntil: z.number().finite().nonnegative().optional(),
  excludedApps: z
    .array(z.object({ bundleId: z.string().min(1).max(300), name: z.string().min(1).max(300) }))
    .max(200)
    .default([]),
  pasteOnSelect: z.boolean().default(true),
  hoverEnabled: z.boolean(),
  retentionDays: z.union([z.literal(1), z.literal(7), z.literal(30)]),
  accelerator: z.string().max(80),
});
export const clipSchema = z.object({
  id: z.string().regex(/^[a-f0-9]{64}$/),
  kind: z.enum(['text', 'image']),
  content: z.string().max(MAX_CLIP_BYTES * 2),
  preview: z.string().max(200000),
  createdAt: z.number().finite(),
  pinned: z.boolean(),
  sourceDevice: z.string().max(100).optional(),
  localOnly: z.boolean().optional(),
});
import {
  compareStamp,
  newest,
  liveEntry,
  manifestSchema,
  stampSchema,
  syncEntrySchema,
  type Stamp,
  type SyncManifest,
} from './clipboard-sync-model';
const syncSchema = z.object({
  device: z.string().uuid(),
  counter: z.number().int().nonnegative(),
  clear: stampSchema.optional(),
  entries: z.record(
    z.string().regex(/^[a-f0-9]{64}$/),
    syncEntrySchema.extend({ seen: stampSchema.optional(), localOnly: z.boolean().optional() }),
  ),
});
const savedSchema = z.object({
  version: z.union([z.literal(1), z.literal(2)]),
  preferences: preferencesSchema,
  clips: z.array(clipSchema).max(MAX_HISTORY_ITEMS),
  sync: syncSchema.optional(),
});
type Saved = z.infer<typeof savedSchema>;

export function clipId(kind: ClipboardClip['kind'], content: string) {
  return createHash('sha256').update(kind).update('\0').update(content).digest('hex');
}
export function excludedClipboardType(types: readonly string[]) {
  return types.some((type) =>
    /org\.nspasteboard\.(ConcealedType|TransientType|AutoGeneratedType)|com\.agilebits\.onepassword/i.test(
      type,
    ),
  );
}
export function clipboardContentType(types: readonly string[]) {
  const image = (
    [
      'image/png',
      'image/jpeg',
      'image/tiff',
      'image/bmp',
      'image/webp',
      'electron application/osclipboard;format="public.png"',
      'electron application/osclipboard;format="Apple PNG pasteboard type"',
      'electron application/osclipboard;format="public.tiff"',
      'electron application/osclipboard;format="NeXT TIFF v4.0 pasteboard type"',
    ] as const
  ).find((type) => types.includes(type));
  // A screenshot can include a temporary file reference alongside its pixels.
  // Skip file-only copies, but never discard an explicit image representation.
  if (image) return image;
  if (types.some((type) => /public\.file-url|NSFilenamesPboardType/i.test(type))) return;
  return types.includes('text/plain') ? 'text/plain' : undefined;
}
function trimHistory(state: Saved, now: number) {
  state.clips = state.clips
    .filter(
      (clip) => clip.pinned || now - clip.createdAt < state.preferences.retentionDays * 86400000,
    )
    .sort((a, b) => Number(b.pinned) - Number(a.pinned) || b.createdAt - a.createdAt);
  let size = 0;
  state.clips = state.clips.filter((clip, index) => {
    size += Buffer.byteLength(clip.content) + Buffer.byteLength(clip.preview);
    return index < MAX_HISTORY_ITEMS && size <= MAX_HISTORY_BYTES;
  });
}

// One private, atomically replaced file; the caller supplies the platform encryption codec.
export class ClipboardHistory {
  private state: Saved = {
    version: 1,
    preferences: { ...DEFAULT_CLIPBOARD_PREFERENCES },
    clips: [],
  };
  private stopped = false;
  private pauseTimer: ReturnType<typeof setTimeout> | undefined;
  private queue: Promise<unknown> = Promise.resolve();
  readonly storage: ClipboardStorage;
  preferencesAvailable = false;
  constructor(
    private path: string,
    private codec: { encode(text: string): Buffer; decode(data: Buffer): string },
    private changed: () => void,
    private now = Date.now,
  ) {
    this.storage = new ClipboardStorage(path, changed);
  }
  async initialize() {
    const data = await this.storage.run('read', async () => {
      let stat;
      try {
        stat = await fs.stat(this.path);
      } catch (error) {
        if ((error as NodeJS.ErrnoException).code === 'ENOENT') return;
        throw error;
      }
      if (stat.size > MAX_HISTORY_BYTES * 3) throw Error('Файл истории слишком большой');
      return fs.readFile(this.path);
    });
    if (data) {
      const decoded = await this.storage.run('decrypt', () => this.codec.decode(data));
      this.state = await this.storage.run('parse', () => savedSchema.parse(JSON.parse(decoded)));
    }
    if (!this.state.sync) {
      this.state.sync = { device: randomUUID(), counter: 0, entries: {} };
      for (const clip of this.state.clips) {
        const stamp = this.stamp(this.state);
        this.state.sync.entries[clip.id] = {
          added: stamp,
          seen: stamp,
          pin: { stamp, value: clip.pinned },
        };
      }
    }
    this.preferencesAvailable = true;
    this.storage.loaded();
    await this.resumeExpiredPause();
    this.schedulePause();
    await this.prune();
  }
  private stamp(next: Saved): Stamp {
    const sync = next.sync!;
    sync.counter = Math.max(sync.counter + 1, Math.floor(this.now()));
    return { counter: sync.counter, device: sync.device };
  }
  persistIdentity() {
    return this.update(() => {}, true);
  }
  get deviceId() {
    return this.state.sync!.device;
  }
  getPreferences() {
    return this.preferencesAvailable
      ? structuredClone({ ...this.state.preferences, paused: this.isPaused() })
      : {
          ...DEFAULT_CLIPBOARD_PREFERENCES,
          paused: true,
          hoverEnabled: false,
          pasteOnSelect: false,
          accelerator: '',
        };
  }
  private isPaused() {
    const preferences = this.state.preferences;
    return (
      preferences.paused &&
      (preferences.pauseUntil === undefined || this.now() < preferences.pauseUntil)
    );
  }
  private schedulePause() {
    clearTimeout(this.pauseTimer);
    const { paused, pauseUntil } = this.state.preferences;
    if (!this.stopped && paused && pauseUntil !== undefined && this.storage.ready) {
      this.pauseTimer = setTimeout(
        () => {
          void this.resumeExpiredPause()
            .catch(() => {})
            .finally(() => this.schedulePause());
        },
        Math.min(2147483647, Math.max(0, pauseUntil - this.now())),
      );
      this.pauseTimer.unref?.();
    }
  }
  resumeExpiredPause() {
    if (!this.storage.ready || !this.state.preferences.paused || this.isPaused())
      return Promise.resolve();
    return this.update((next) => {
      if (next.preferences.pauseUntil !== undefined && this.now() >= next.preferences.pauseUntil) {
        next.preferences.paused = false;
        delete next.preferences.pauseUntil;
      }
    });
  }
  stop() {
    this.stopped = true;
    clearTimeout(this.pauseTimer);
  }
  snapshot(includeImageContent = true) {
    return structuredClone({
      version: this.state.version,
      preferences: this.getPreferences(),
      clips: includeImageContent
        ? this.state.clips
        : this.state.clips.map((clip) => (clip.kind === 'image' ? { ...clip, content: '' } : clip)),
    });
  }
  private update(operation: (next: Saved) => void, force = false) {
    const result = this.queue.then(async () => {
      this.storage.requireReady();
      const next = structuredClone(this.state);
      operation(next);
      trimHistory(next, this.now());
      if (!force && JSON.stringify(next) === JSON.stringify(this.state)) return;
      const encoded = await this.storage.run('encrypt', () =>
        this.codec.encode(JSON.stringify(next)),
      );
      await this.storage.run('write', async () => {
        await fs.mkdir(dirname(this.path), { recursive: true, mode: 0o700 });
        const temporary = this.path + '.tmp';
        await fs.writeFile(temporary, encoded, { mode: 0o600 });
        await fs.rename(temporary, this.path);
      });
      this.state = next;
      this.schedulePause();
      this.changed();
    });
    this.queue = result.catch(() => {});
    return result;
  }
  add(kind: ClipboardClip['kind'], content: string, preview: string, sourceBundleId?: string) {
    if (!content || Buffer.byteLength(content) > MAX_CLIP_BYTES || preview.length > 200000)
      return Promise.resolve();
    return this.update((next) => {
      if (
        next.preferences.paused &&
        (next.preferences.pauseUntil === undefined || this.now() < next.preferences.pauseUntil)
      )
        return;
      if (
        next.preferences.excludedApps.length &&
        (!sourceBundleId ||
          next.preferences.excludedApps.some((app) => app.bundleId === sourceBundleId))
      )
        return;
      const id = clipId(kind, content);
      const existing = next.clips.find((clip) => clip.id === id);
      next.clips = next.clips.filter((clip) => clip.id !== id);
      const stamp = this.stamp(next);
      next.sync!.entries[id] = {
        ...next.sync!.entries[id],
        added: stamp,
        seen: stamp,
        pin: { stamp, value: existing?.pinned || false },
      };
      next.clips.unshift({
        id,
        kind,
        content,
        preview,
        createdAt: this.now(),
        pinned: existing?.pinned || false,
        ...(next.sync!.entries[id].localOnly ? { localOnly: true } : {}),
      });
    });
  }
  preferences(patch: Partial<ClipboardPreferences>) {
    return this.update((next) => {
      // Older binaries must fail closed rather than silently dropping privacy flags.
      if (
        patch.paused !== undefined ||
        patch.pauseUntil !== undefined ||
        patch.excludedApps !== undefined
      )
        next.version = 2;
      next.preferences = preferencesSchema.parse({ ...next.preferences, ...patch });
      if (patch.paused !== undefined && patch.pauseUntil === undefined)
        delete next.preferences.pauseUntil;
      if (!next.preferences.paused) delete next.preferences.pauseUntil;
    });
  }
  pin(id: string, pinned: boolean) {
    return this.update((next) => {
      const clip = next.clips.find((item) => item.id === id);
      if (!clip) throw Error('Запись уже удалена');
      clip.pinned = pinned;
      next.sync!.entries[id] = {
        ...next.sync!.entries[id],
        pin: { stamp: this.stamp(next), value: pinned },
      };
    });
  }
  localOnly(id: string, value: boolean) {
    return this.update((next) => {
      const clip = next.clips.find((item) => item.id === id);
      if (!clip) throw Error('Запись уже удалена');
      if (!!clip.localOnly === value) return;
      next.version = 2;
      clip.localOnly = value || undefined;
      const entry = next.sync!.entries[id];
      entry.localOnly = value || undefined;
      if (!value) {
        const stamp = this.stamp(next);
        entry.added = stamp;
        entry.seen = stamp;
        entry.pin = { stamp, value: clip.pinned };
      }
    });
  }
  remove(id: string) {
    return this.update((next) => {
      next.clips = next.clips.filter((clip) => clip.id !== id);
      next.sync!.entries[id] = { ...next.sync!.entries[id], deleted: this.stamp(next) };
    });
  }
  clear() {
    return this.update((next) => {
      next.clips = [];
      next.sync!.clear = this.stamp(next);
    });
  }
  manifest(): SyncManifest {
    this.storage.requireReady();
    const sync = this.state.sync!;
    return structuredClone({
      version: 1,
      clear: sync.clear,
      entries: Object.fromEntries(
        Object.entries(sync.entries)
          .filter(([, entry]) => !entry.localOnly)
          .map(([id, { seen: _seen, localOnly: _localOnly, ...entry }]) => [id, entry]),
      ),
      available: this.state.clips.filter((clip) => !clip.localOnly).map((clip) => clip.id),
    });
  }
  // Advance deletion/pin metadata before requesting content. Seen versions survive
  // local expiry, so an unchanged remote copy cannot undo local retention.
  async mergeManifest(input: unknown) {
    this.storage.requireReady();
    const remote = manifestSchema.parse(input);
    const current = this.state.sync!;
    const changed =
      compareStamp(remote.clear, current.clear) > 0 ||
      Object.entries(remote.entries).some(([id, entry]) => {
        const local = current.entries[id];
        if (local?.localOnly)
          return [entry.added, entry.deleted, entry.pin?.stamp].some(
            (stamp) => stamp && stamp.counter > current.counter,
          );
        return (
          !local ||
          compareStamp(entry.added, local.added) > 0 ||
          compareStamp(entry.deleted, local.deleted) > 0 ||
          compareStamp(entry.pin?.stamp, local.pin?.stamp) > 0
        );
      });
    if (changed)
      await this.update((next) => {
        const sync = next.sync!;
        if (compareStamp(remote.clear, sync.clear) > 0) {
          // A clear also removes entries accumulated on an offline Mac before it
          // receives the command. Record their exact versions, so newer copies
          // made on another Mac after clearing can still be retained.
          for (const entry of Object.values(sync.entries).filter((entry) => !entry.localOnly))
            entry.deleted = newest(entry.deleted, newest(entry.added, remote.clear));
        }
        sync.clear = newest(sync.clear, remote.clear);
        if (remote.clear) sync.counter = Math.max(sync.counter, remote.clear.counter);
        for (const [id, incoming] of Object.entries(remote.entries)) {
          const local = sync.entries[id] || {};
          for (const stamp of [incoming.added, incoming.deleted, incoming.pin?.stamp])
            if (stamp) sync.counter = Math.max(sync.counter, stamp.counter);
          if (local.localOnly) continue;
          if (
            incoming.pin?.value &&
            compareStamp(incoming.pin.stamp, local.pin?.stamp) > 0 &&
            !next.clips.some((clip) => clip.id === id)
          )
            local.seen = undefined;
          sync.entries[id] = {
            ...local,
            added: newest(local.added, incoming.added),
            deleted: newest(local.deleted, incoming.deleted),
            pin: compareStamp(incoming.pin?.stamp, local.pin?.stamp) > 0 ? incoming.pin : local.pin,
          };
        }
        next.clips = next.clips.filter(
          (clip) => clip.localOnly || liveEntry(sync.entries[clip.id], sync.clear),
        );
        for (const clip of next.clips.filter((clip) => !clip.localOnly))
          clip.pinned = sync.entries[clip.id].pin?.value ?? false;
      });
    return remote.available.filter((id) => {
      const entry = this.state.sync!.entries[id];
      return (
        entry &&
        !entry.localOnly &&
        liveEntry(entry, this.state.sync!.clear) &&
        compareStamp(entry.added, entry.seen) > 0
      );
    });
  }
  transfer(id: string) {
    const clip = this.state.clips.find((item) => item.id === id);
    const stamp = this.state.sync!.entries[id]?.seen;
    return clip && !clip.localOnly && stamp ? structuredClone({ clip, stamp }) : undefined;
  }
  async receive(input: unknown, sourceDevice: string) {
    this.storage.requireReady();
    const { clip, stamp } = z.object({ clip: clipSchema, stamp: stampSchema }).parse(input);
    if (
      !clip.content ||
      Buffer.byteLength(clip.content) > MAX_CLIP_BYTES ||
      clipId(clip.kind, clip.content) !== clip.id
    )
      throw Error('Некорректная запись буфера');
    if (clip.kind === 'image') {
      const png = Buffer.from(clip.content, 'base64');
      if (
        !/^[A-Za-z0-9+/]+={0,2}$/.test(clip.content) ||
        png.length > MAX_IMAGE_BYTES ||
        !png.subarray(0, 8).equals(Buffer.from([137, 80, 78, 71, 13, 10, 26, 10])) ||
        !/^data:image\/png;base64,[A-Za-z0-9+/]+={0,2}$/.test(clip.preview)
      )
        throw Error('Некорректное изображение буфера');
    } else clip.preview = clip.content.slice(0, 400);
    await this.update((next) => {
      const sync = next.sync!;
      const entry = sync.entries[clip.id];
      if (
        !entry ||
        entry.localOnly ||
        clip.localOnly ||
        compareStamp(stamp, entry.added) !== 0 ||
        !liveEntry(entry, sync.clear) ||
        compareStamp(stamp, entry.seen) <= 0
      )
        return;
      entry.seen = stamp;
      next.clips = next.clips.filter((item) => item.id !== clip.id);
      next.clips.push({
        ...clip,
        pinned: entry.pin?.value ?? false,
        sourceDevice: clip.sourceDevice || sourceDevice,
      });
    });
  }
  prune() {
    if (!this.storage.ready) return Promise.resolve();
    if (
      !this.state.clips.some(
        (clip) =>
          !clip.pinned &&
          this.now() - clip.createdAt >= this.state.preferences.retentionDays * 86400000,
      )
    )
      return Promise.resolve();
    return this.update(() => {});
  }
  flush() {
    return this.queue;
  }
}
