#include <CoreFoundation/CoreFoundation.h>
#include <Security/Security.h>
#include <errno.h>
#include <libproc.h>
#include <pthread.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/stat.h>
#include <time.h>
#include <unistd.h>

/* Generated by the Swift development tool. No runtime requirement override. */
#include "PolkaBrokerConfiguration.h"

static void erase(void *memory, size_t count) {
  volatile unsigned char *bytes = memory;
  while (count--) *bytes++ = 0;
}

static int failure(const char *message) {
  fprintf(stderr, "Polka development Keychain broker: %s.\n", message);
  return 1;
}

static int authorized_parent(void) {
  const pid_t parent = getppid();
  if (parent <= 1 || getuid() != geteuid() || getgid() != getegid()) return 0;
  struct proc_bsdinfo identity;
  if (proc_pidinfo(parent, PROC_PIDTBSDINFO, 0, &identity, sizeof(identity)) != (int)sizeof(identity) ||
      identity.pbi_uid != geteuid() || identity.pbi_ruid != getuid()) return 0;
  CFNumberRef pid = CFNumberCreate(NULL, kCFNumberIntType, &parent);
  if (!pid) return 0;
  const void *keys[] = {kSecGuestAttributePid};
  const void *values[] = {pid};
  CFDictionaryRef attributes = CFDictionaryCreate(NULL, keys, values, 1,
      &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks);
  SecCodeRef code = NULL;
  SecRequirementRef requirement = NULL;
  CFStringRef expression = CFStringCreateWithCString(NULL,
      POLKA_PARENT_REQUIREMENT, kCFStringEncodingUTF8);
  OSStatus status = attributes && expression
      ? SecCodeCopyGuestWithAttributes(NULL, attributes, kSecCSDefaultFlags, &code)
      : errSecAllocate;
  if (status == errSecSuccess)
    status = SecRequirementCreateWithString(expression, kSecCSDefaultFlags, &requirement);
  if (status == errSecSuccess)
    status = SecCodeCheckValidity(code, kSecCSStrictValidate, requirement);
  if (requirement) CFRelease(requirement);
  if (code) CFRelease(code);
  if (expression) CFRelease(expression);
  if (attributes) CFRelease(attributes);
  CFRelease(pid);
  return status == errSecSuccess && getppid() == parent;
}

/* A Keychain authorization prompt may block indefinitely. Reaping follows parent
   death even when the main app exits through a terminal signal instead of AppKit. */
static void *monitor_parent(void *argument) {
  const pid_t parent = (pid_t)(intptr_t)argument;
  for (;;) {
    if (getppid() != parent) _exit(1);
    struct timespec remaining = { .tv_sec = 0, .tv_nsec = 200000000 };
    while (nanosleep(&remaining, &remaining) != 0 && errno == EINTR) {
      if (getppid() != parent) _exit(1);
    }
  }
  return NULL;
}

static int start_parent_monitor(pid_t parent) {
  pthread_attr_t attributes;
  if (parent <= 1 || pthread_attr_init(&attributes) != 0) return 0;
  int status = pthread_attr_setdetachstate(&attributes, PTHREAD_CREATE_DETACHED);
  pthread_t thread;
  if (status == 0)
    status = pthread_create(&thread, &attributes, monitor_parent, (void *)(intptr_t)parent);
  pthread_attr_destroy(&attributes);
  return status == 0 && getppid() == parent;
}

static CFMutableDictionaryRef make_query(void) {
  CFMutableDictionaryRef query = CFDictionaryCreateMutable(NULL, 0,
      &kCFTypeDictionaryKeyCallBacks, &kCFTypeDictionaryValueCallBacks);
  if (!query) return NULL;
  CFDictionarySetValue(query, kSecClass, kSecClassGenericPassword);
  CFDictionarySetValue(query, kSecAttrService, CFSTR("polka Safe Storage"));
  CFDictionarySetValue(query, kSecAttrAccount, CFSTR("polka"));
  CFDictionarySetValue(query, kSecMatchLimit, kSecMatchLimitOne);
  CFDictionarySetValue(query, kSecReturnData, kCFBooleanTrue);
  /* POLKA_FIXTURE_QUERY_SCOPE: synthetic tests may inject an isolated search list here. */
  return query;
}

static OSStatus create_secret(CFDictionaryRef query) {
  unsigned char random[16] = {0};
  unsigned char encoded[24] = {0};
  OSStatus status = SecRandomCopyBytes(kSecRandomDefault, sizeof(random), random);
  if (status != errSecSuccess) {
    erase(random, sizeof(random));
    return status;
  }
  static const unsigned char alphabet[] =
      "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
  size_t out = 0;
  for (size_t index = 0; index < sizeof(random); index += 3) {
    size_t remaining = sizeof(random) - index;
    uint32_t value = (uint32_t)random[index] << 16;
    if (remaining > 1) value |= (uint32_t)random[index + 1] << 8;
    if (remaining > 2) value |= random[index + 2];
    encoded[out++] = alphabet[(value >> 18) & 63];
    encoded[out++] = alphabet[(value >> 12) & 63];
    encoded[out++] = remaining > 1 ? alphabet[(value >> 6) & 63] : '=';
    encoded[out++] = remaining > 2 ? alphabet[value & 63] : '=';
  }
  CFMutableDictionaryRef attributes = CFDictionaryCreateMutableCopy(NULL, 0, query);
  CFDataRef secret = CFDataCreate(NULL, encoded, sizeof(encoded));
  if (!attributes || !secret) {
    status = errSecAllocate;
  } else {
    CFDictionaryRemoveValue(attributes, kSecMatchLimit);
    CFDictionaryRemoveValue(attributes, kSecReturnData);
    CFDictionarySetValue(attributes, kSecValueData, secret);
    /* POLKA_FIXTURE_ADD_SCOPE: synthetic tests may inject a fixed destination keychain here. */
    status = SecItemAdd(attributes, NULL);
  }
  if (secret) CFRelease(secret);
  if (attributes) CFRelease(attributes);
  erase(random, sizeof(random));
  erase(encoded, sizeof(encoded));
  return status;
}

int main(int argc, const char **argv) {
  const int allow_create = argc == 2 && strcmp(argv[1], "--allow-create") == 0;
  if (argc != 1 && !allow_create) return failure("invalid arguments");
  struct stat output;
  if (fstat(STDOUT_FILENO, &output) != 0 || !S_ISFIFO(output.st_mode))
    return failure("output must be a private pipe");
  /* Authorization always precedes even a missing-item query or creation attempt. */
  if (!authorized_parent()) return failure("caller is not authorized");
  if (!start_parent_monitor(getppid())) return failure("parent monitor unavailable");
  CFMutableDictionaryRef query = make_query();
  if (!query) return failure("allocation failed");
  CFTypeRef result = NULL;
  OSStatus status = SecItemCopyMatching(query, &result);
  if (status == errSecItemNotFound && allow_create) {
    status = create_secret(query);
    if (status == errSecSuccess || status == errSecDuplicateItem)
      status = SecItemCopyMatching(query, &result);
  }
  CFRelease(query);
  if (status != errSecSuccess || !result || CFGetTypeID(result) != CFDataGetTypeID()) {
    if (result) CFRelease(result);
    return failure("access failed or key is missing");
  }
  CFDataRef secret = (CFDataRef)result;
  CFIndex length = CFDataGetLength(secret);
  if (length <= 0 || length > 4096) {
    CFRelease(secret);
    return failure("invalid key");
  }
  if (!authorized_parent()) {
    CFRelease(secret);
    return failure("caller is no longer authorized");
  }
  const UInt8 *bytes = CFDataGetBytePtr(secret);
  CFIndex written = 0;
  while (written < length) {
    ssize_t count = write(STDOUT_FILENO, bytes + written, (size_t)(length - written));
    if (count < 0 && errno == EINTR) continue;
    if (count <= 0) {
      CFRelease(secret);
      return failure("output failed");
    }
    written += count;
  }
  CFRelease(secret);
  return 0;
}
